import io

from django.http import HttpResponse
from rest_framework.views import APIView
from rest_framework import status, serializers
from rest_framework.response import Response

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4


class ProjectReportSerializer(serializers.Serializer):
    projectId = serializers.CharField(required=False, allow_blank=True)
    project = serializers.DictField(required=False, allow_null=True)
    overviewStats = serializers.DictField(required=False, allow_null=True)
    overviewInsights = serializers.DictField(required=False, allow_null=True)
    reportingProjectInfo = serializers.DictField(required=False, allow_null=True)
    membersOverview = serializers.DictField(required=False, allow_null=True)
    reportingMembers = serializers.DictField(required=False, allow_null=True)
    memberStats = serializers.DictField(required=False, allow_null=True)
    taskStatusCounts = serializers.DictField(required=False, allow_null=True)
    priorityOverview = serializers.DictField(required=False, allow_null=True)
    deadlineStats = serializers.DictField(required=False, allow_null=True)
    overdueTasks = serializers.DictField(required=False, allow_null=True)
    completedEarlyTasks = serializers.DictField(required=False, allow_null=True)
    completedLateTasks = serializers.DictField(required=False, allow_null=True)
    lastUpdatedTasks = serializers.DictField(required=False, allow_null=True)
    projectLogs = serializers.DictField(required=False, allow_null=True)
    timeSheets = serializers.DictField(required=False, allow_null=True)
    estimatedVsActual = serializers.DictField(required=False, allow_null=True)


def generate_pdf_report(data: dict) -> bytes:
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    def safe_get(d, key, default=None):
        if isinstance(d, dict):
            return d.get(key, default)
        return default

    def unwrap_body(value):
        if isinstance(value, dict) and "body" in value:
            return value.get("body")
        return value

    def normalize_list(value):
        if not value:
            return []
        if isinstance(value, list):
            return value
        if isinstance(value, dict):
            items = value.get("items")
            if isinstance(items, list):
                return items
            data_list = value.get("data")
            if isinstance(data_list, list):
                return data_list
            return [value]
        return []

    # ----- Extract and unwrap main sections -----
    project_resp = data.get("project")
    project = unwrap_body(project_resp) or {}

    project_id = data.get("projectId") or safe_get(project, "id", "N/A")
    project_name = safe_get(project, "name", "N/A")
    project_status = safe_get(project, "status", "N/A")
    project_category = safe_get(project, "category_name", "N/A")

    overview_stats_resp = data.get("overviewStats")
    overview_stats = unwrap_body(overview_stats_resp) or {}

    task_status_resp = data.get("taskStatusCounts")
    task_status_body = unwrap_body(task_status_resp)
    task_status_counts = normalize_list(task_status_body)

    members_overview_resp = data.get("membersOverview")
    members_overview_body = unwrap_body(members_overview_resp)
    members = normalize_list(members_overview_body)

    last_updated_resp = data.get("lastUpdatedTasks")
    last_updated_body = unwrap_body(last_updated_resp)
    last_updated_tasks = normalize_list(last_updated_body)

    # ----- PAGE 1: Big title -----
    title_text = f"Project Report for {project_name}"
    title_font = "Helvetica-Bold"
    title_size = 28

    pdf.setFont(title_font, title_size)
    title_width = pdf.stringWidth(title_text, title_font, title_size)
    title_x = (width - title_width) / 2
    title_y = height / 2

    pdf.drawString(title_x, title_y, title_text)

    # Footer on page 1
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawCentredString(width / 2, 40, "Generated by WorkPrism")

    pdf.showPage()

    # ----- PAGE 2: Details, overview, tasks, members -----
    y = height - 50

    # Page header
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Project Report")
    y -= 24

    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, y, f"Project ID: {project_id}")
    y -= 15
    pdf.drawString(50, y, f"Project Name: {project_name}")
    y -= 15
    pdf.drawString(50, y, f"Status: {project_status}")
    y -= 15
    pdf.drawString(50, y, f"Category: {project_category}")
    y -= 25

    # Overview section
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "Overview")
    y -= 18
    pdf.setFont("Helvetica", 10)

    # Data for paragraph
    done_count = safe_get(overview_stats, "done_task_count", None)
    pending_count = safe_get(overview_stats, "pending_task_count", None)
    total_tasks = None
    if done_count is not None and pending_count is not None:
        try:
            total_tasks = int(done_count) + int(pending_count)
        except:
            total_tasks = None

    member_count = len(members) if members else 0

    # Construct paragraph text
    paragraph_lines = []
    line = f"This is a report for the project '{project_name}'."
    paragraph_lines.append(line)

    # Task summary
    if total_tasks is not None:
        paragraph_lines.append(
            f"The project currently has a total of {total_tasks} tasks, "
            f"with {pending_count} pending and {done_count} completed."
        )
    elif pending_count is not None or done_count is not None:
        pending_str = pending_count if pending_count is not None else "an unknown number of"
        done_str = done_count if done_count is not None else "an unknown number of"
        paragraph_lines.append(
            f"The project has {pending_str} pending tasks and {done_str} completed tasks."
        )
    else:
        paragraph_lines.append(
            "Task completion statistics are currently unavailable."
        )

    # Members summary
    if member_count > 0:
        paragraph_lines.append(
            f"The project team consists of {member_count} member{'s' if member_count != 1 else ''}."
        )
    else:
        paragraph_lines.append("No team member information is available for this project.")

    # Write paragraph into PDF with line wrapping
    for p_line in paragraph_lines:
        text_width = pdf.stringWidth(p_line, "Helvetica", 10)
        max_width = width - 100
        if text_width <= max_width:
            pdf.drawString(60, y, p_line)
            y -= 14
        else:
            words = p_line.split(" ")
            current = ""
            for w in words:
                test = current + w + " "
                if pdf.stringWidth(test, "Helvetica", 10) <= max_width:
                    current = test
                else:
                    pdf.drawString(60, y, current.strip())
                    y -= 14
                    current = w + " "
            if current:
                pdf.drawString(60, y, current.strip())
                y -= 14

    y -= 6  

    # Tasks by Status
    if y < 120:
        pdf.showPage()
        y = height - 50

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "Tasks by Status")
    y -= 18
    pdf.setFont("Helvetica", 10)

    # Build a map of status -> tasks (using lastUpdatedTasks for examples)
    status_to_tasks = {}
    for t in last_updated_tasks:
        status_name = safe_get(t, "status", "Unknown")
        status_to_tasks.setdefault(status_name, []).append(t)

    for status_item in task_status_counts:
        # Some APIs use "name", some "status"
        status_name = safe_get(status_item, "name", safe_get(status_item, "status", "Unknown"))
        count = safe_get(status_item, "count", safe_get(status_item, "y", "N/A"))

        pdf.drawString(60, y, f"{status_name}: {count}")
        y -= 14

        # Example task bullets under this status, if we have any
        tasks_for_status = status_to_tasks.get(status_name, [])
        for t in tasks_for_status[:5]:  # limit a few bullets per status
            task_title = safe_get(t, "name", safe_get(t, "title", "Untitled task"))
            end_date = safe_get(t, "end_date", "N/A")
            bullet_text = f"* {task_title} (End Date: {end_date})"
            pdf.drawString(80, y, bullet_text)
            y -= 12
            if y < 80:
                # Footer for this page before going to next
                pdf.setFont("Helvetica-Oblique", 10)
                pdf.drawCentredString(width / 2, 40, "Generated by WorkPrism")
                pdf.showPage()
                y = height - 50
                pdf.setFont("Helvetica", 10)

        y -= 6  # small gap between statuses
        if y < 80:
            pdf.setFont("Helvetica-Oblique", 10)
            pdf.drawCentredString(width / 2, 40, "Generated by WorkPrism")
            pdf.showPage()
            y = height - 50
            pdf.setFont("Helvetica", 10)

    # Team Members
    if y < 120:
        pdf.setFont("Helvetica-Oblique", 10)
        pdf.drawCentredString(width / 2, 40, "Generated by WorkPrism")
        pdf.showPage()
        y = height - 50

    if members:
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(50, y, "Team Members")
        y -= 18
        pdf.setFont("Helvetica", 10)

        for m in members[:20]:
            name = safe_get(m, "name", safe_get(m, "full_name", "Unknown"))
            assigned = safe_get(m, "task_count", "N/A")
            completed = safe_get(m, "done_task_count", "N/A")
            pending = safe_get(m, "pending_task_count", "N/A")
            overdue = safe_get(m, "overdue_task_count", "N/A")

            line = f"{name} — Assigned: {assigned}, Completed: {completed}, Pending: {pending}, Overdue: {overdue}"
            pdf.drawString(60, y, line)
            y -= 14

            if y < 80:
                pdf.setFont("Helvetica-Oblique", 10)
                pdf.drawCentredString(width / 2, 40, "Generated by WorkPrism")
                pdf.showPage()
                y = height - 50
                pdf.setFont("Helvetica", 10)

    # Final footer on last page
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawCentredString(width / 2, 40, "Generated by WorkPrism")

    pdf.showPage()
    pdf.save()

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


class ReportView(APIView):
    http_method_names = ["post"]

    def post(self, request, filetype, *args, **kwargs):
        allowed_filetypes = ["pdf"]
        if filetype not in allowed_filetypes:
            return Response(
                {"detail": "Unsupported file type."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        
        print("------------------------------")
        print(request.data)
        print("------------------------------")

        serializer = ProjectReportSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        data = serializer.validated_data
        pdf_bytes = generate_pdf_report(data)

        filename = f"project-report-{data.get('projectId', 'project')}.pdf"

        response = HttpResponse(pdf_bytes, content_type="application/pdf")
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        return response
